name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install gtk and sdl2
      run: sudo apt install libsdl2-dev libsdl2-ttf-dev libgtk-3-dev   
    - name: Build
      run: cargo build --verbose -r
    - name: upload it to timelessnesses cdn
      run: echo ${{ secrets.priv_ssh }} > out.pub && scp -i out.pub ./target/release/nothing_sdl2_rust root@statics.timelessnesses.me:/root/statics