name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install gtk and sdl2
      run: sudo apt install libsdl2-dev libsdl2-ttf-dev libgtk-3-dev libgtk-2-dev
    - name: Build
      run: cargo build --verbose
